version: "3.9"

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123study
      - MYSQL_DATABASE=controledecaixa
    command: --default-authentication-plugin=mysql_native_password

  spring-app:
    container_name: spring
    restart: always
    image: pedrodurand/backend-controlecaixa:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/controledecaixa
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql123study
    depends_on:
      - mysql-db