version: "3.9"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123study
      - MYSQL_DATABASE=controledecaixa
  spring-app:
    container_name: spring
    image: pedrodurand/backend3-controlecaixa:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/controledecaixa
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql123study
    depends_on:
      - mysql-db
  spa-app:
    container_name: react
    image: pedrodurand/frontend-controlecaixa:latest
    ports:
      - "3000:3000"
    depends_on:
      - spring-app
